"""Pre-commit hook for functional validation."""

import shutil
import subprocess
import sys
from pathlib import Path


HOOK_SCRIPT = """#!/bin/bash
# Auto-generated by Orca. Do not edit manually.
# Pre-commit hook for functional validation.

set -e

ORCA_HOOK_LOG=".git/hooks/orca-hook.log"

# Run validation, capturing output
if orca validate --staged 2>&1; then
    echo "✓ Orca validation passed" >> "$ORCA_HOOK_LOG" 2>/dev/null || true
    exit 0
else
    echo "✗ Orca validation failed - commit blocked" >> "$ORCA_HOOK_LOG" 2>/dev/null || true
    exit 1
fi
"""


def install_hooks(project_path: Path | None = None) -> bool:
    """Install pre-commit hook in .git/hooks/.

    Creates .git/hooks/pre-commit that runs:
        orca validate --staged

    Returns True if installed, False if skipped/already exists.
    """
    if project_path is None:
        project_path = Path.cwd()

    git_dir = project_path / ".git"
    if not git_dir.exists():
        return False

    hooks_dir = git_dir / "hooks"
    hook_path = hooks_dir / "pre-commit"

    # Check if hook already installed
    if hook_path.exists():
        content = hook_path.read_text()
        if "# Auto-generated by Orca" in content:
            return False  # Already installed

    # Install the hook
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path.write_text(HOOK_SCRIPT)
    hook_path.chmod(0o755)

    return True


def run_pre_commit_validation(commit_msg: str | None = None) -> bool:
    """Run pre-commit validation for staged changes.

    Returns True if validation passes or hook skipped.
    Returns False if validation fails (commit should be blocked).
    """
    # Check if orca is available
    orca_path = shutil.which("orca")
    if not orca_path:
        print(
            "warning: 'orca' command not found in PATH, skipping validation",
            file=sys.stderr,
        )
        return True

    # Get staged files
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
            capture_output=True,
            text=True,
            check=True,
        )
        staged_files = [f.strip() for f in result.stdout.splitlines() if f.strip()]
    except subprocess.CalledProcessError:
        return True  # Skip on git error

    if not staged_files:
        return True  # Nothing to validate

    # Run validation on staged files
    try:
        result = subprocess.run(
            ["orca", "validate", "--staged"],
            capture_output=True,
            text=True,
        )
        return result.returncode == 0
    except Exception:
        return True  # Skip on error


# Make module executable as script
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Orca pre-commit hook")
    parser.add_argument("--commit-msg", help="Commit message (ignored)")
    args = parser.parse_args()

    success = run_pre_commit_validation(args.commit_msg)
    sys.exit(0 if success else 1)
